export const SET_TOPIC_DATA = "SET_TOPIC_DATA";
export const SET_PLAYER_PAGE = "SET_PLAYER_PAGE";
export const SET_TOPIC_PAGE = "SET_TOPIC_PAGE";
export const SET_MESSAGES = "SET_MESSAGES";
export const INCREMENT_ROUND = "INCREMENT_ROUND";
